version: "3.9"

services:

  # =================================
  # 1. Workflow & Orchestrazione
  # =================================
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - QUEUE_MODE=${QUEUE_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ${N8N_DATA_PATH}:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    networks:
      - backend
      - zerotier

  # =================================
  # 2. Database
  # =================================
  postgres:
    container_name: postgres
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - backend
    command: >
      bash -c "
      docker-entrypoint.sh postgres &
      sleep 5 &&
      psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE EXTENSION IF NOT EXISTS vector;' &&
      fg"

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    volumes:
      - ${REDIS_DATA_PATH}:/data
    networks:
      - backend

  # =================================
  # 3. AI / TTS / STT
  # =================================
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=${OLLAMA_GPU}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - backend

  wyoming:
    container_name: wyoming
    image: ghcr.io/utente/wyoming:latest
    restart: unless-stopped
    volumes:
      - ${WYOMING_CACHE_VOLUME}:${WYOMING_CACHE_PATH}
    networks:
      - backend

  # =================================
  # 4. Storage
  # =================================
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server ${MINIO_DATA_PATH}
    volumes:
      - ${MINIO_DATA_VOLUME}:${MINIO_DATA_PATH}
    networks:
      - backend

  # =================================
  # 5. File Management
  # =================================
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    environment:
      - PUID=${FILEBROWSER_PUID}
      - PGID=${FILEBROWSER_PGID}
    volumes:
      - ${FILEBROWSER_DATA_VOLUME}:${FILEBROWSER_DATA_PATH}
    networks:
      - backend

  # =================================
  # 6. Home Automation
  # =================================
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - ${HOMEASSISTANT_DATA_VOLUME}:${HOMEASSISTANT_CONFIG_PATH}
    network_mode: host
    devices:
      - ${HOMEASSISTANT_DEVICE}:${HOMEASSISTANT_DEVICE}
    networks:
      - backend
      - zerotier

  # =================================
  # 7. GIS / QGIS
  # =================================
  qgis-server:
    container_name: qgis-server
    image: kartoza/qgis-server:latest
    restart: unless-stopped
    volumes:
      - ${QGIS_PROJECTS_VOLUME}:${QGIS_PROJECTS_PATH}
    networks:
      - backend

  # =================================
  # 8. Management / Admin
  # =================================
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    networks:
      - backend

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    networks:
      - backend

  # =================================
  # 9. Networking - Remote Access
  # =================================
  zerotier:
    container_name: zerotier
    image: zt0/zerotier-container
    restart: unless-stopped
    environment:
      - ZT_NETWORK_ID=${ZEROTIER_NETWORK_ID}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - backend

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - backend

# =================================
# Volumi locali
# =================================
volumes:
  n8n_data:
  pg_data:
  redis_data:
  wyoming_cache:
  minio_data:
  filebrowser_data:
  qgis_projects:
  homeassistant_data:

# =================================
# Rete interna
# =================================
networks:
  backend:
    driver: bridge
  zerotier:
    external: true
